- name: craete ec2 and r53 
  hosts: local 
  connection: local
  become: yes  
  vars: 
   ami_id: ami-0220d79f3f480ecf5
   sg_id: sg-03f403f2be7db3bbc # replace with your sg ID
   zone_id: "Z090071510OXTGFIDW0RR" # replace with your zone ID
   domain_name: "sivadevops.space" # replace with your domain-name
    # we can pass instances through command line using -e
   instances: 
    - mongodb
   # - redis
   # - mysql
   # - rabbitmq
  tasks: 
  - name: create ec2-instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      sg_id: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
       Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output 

  - name: print the ec2_output 
    ansible.builtin.debug: 
     msg: "{{ ec2_output }}"

